//! Demo Mode - Pre-loaded sample data for offline demonstrations
//! 
//! Provides realistic network topology with sample devices, vulnerabilities, and alerts

use host_discovery::{HostInfo, ScanResult, VulnerabilityInfo, AlertRecord, AlertType, AlertSeverity};


/// Generate demo scan result with realistic sample data
pub fn generate_demo_scan() -> ScanResult {
    let hosts = generate_demo_hosts();
    
    ScanResult {
        interface_name: "eth0".to_string(),
        local_ip: "192.168.1.100".to_string(),
        local_mac: "00:00:00:00:00:00".to_string(),
        subnet: "192.168.1.0/24".to_string(),
        scan_method: "Demo".to_string(),
        arp_discovered: hosts.len(),
        icmp_discovered: hosts.len(),
        total_hosts: hosts.len(),
        scan_duration_ms: 2500,
        active_hosts: hosts,
    }
}

/// Generate 16 realistic demo devices with variety in vendors, types, and risk levels
fn generate_demo_hosts() -> Vec<HostInfo> {
    vec![
        // 1. Gateway Router (TP-Link)
        HostInfo {
            ip: "192.168.1.1".to_string(),
            mac: "34:4a:c3:22:6f:90".to_string(),
            vendor: Some("TP-Link Technologies Co., Ltd.".to_string()),
            hostname: Some("Router.local".to_string()),
            device_type: "Router".to_string(),
            os_guess: Some("Linux/Unix/macOS".to_string()),
            response_time_ms: Some(2),
            ttl: Some(64),
            open_ports: vec![80, 443, 22],
            risk_score: 35,
            discovery_method: "Demo".to_string(),
            system_description: None,
            uptime_seconds: None,
            is_randomized: false,
            neighbors: vec![],
            vulnerabilities: vec![],
            port_warnings: vec![],
            security_grade: "B".to_string(),
        },
        
        // 2. Windows PC - HIGH RISK
        HostInfo {
            ip: "192.168.1.10".to_string(),
            mac: "00:0c:29:5a:8f:1d".to_string(),
            vendor: Some("Dell Inc.".to_string()),
            hostname: Some("WIN-PC-001".to_string()),
            device_type: "Desktop".to_string(),
            os_guess: Some("Windows".to_string()),
            response_time_ms: Some(5),
            ttl: Some(128),
            open_ports: vec![445, 3389, 135],
            risk_score: 85,
            discovery_method: "Demo".to_string(),
            system_description: None,
            uptime_seconds: None,
            is_randomized: false,
            neighbors: vec![],
            vulnerabilities: vec![
                VulnerabilityInfo {
                    cve_id: "CVE-2017-0144".to_string(),
                    severity: "Critical".to_string(),
                    description: "EternalBlue SMBv1 Remote Code Execution".to_string(),
                    cvss_score: Some(9.3),
                },
                VulnerabilityInfo {
                    cve_id: "CVE-2019-0708".to_string(),
                    severity: "Critical".to_string(),
                    description: "BlueKeep RDP Remote Code Execution".to_string(),
                    cvss_score: Some(9.8),
                },
            ],
            port_warnings: vec![],
            security_grade: "F".to_string(),
        },
        
        // 3. Android Phone (Randomized MAC)
        HostInfo {
            ip: "192.168.1.25".to_string(),
            mac: "d2:81:c8:45:6b:71".to_string(),
            vendor: Some("Private Device (Randomized MAC)".to_string()),
            hostname: Some("Galaxy-S23".to_string()),
            device_type: "Phone".to_string(),
            os_guess: Some("Linux/Unix/macOS".to_string()),
            response_time_ms: Some(12),
            ttl: Some(64),
            open_ports: vec![],
            risk_score: 10,
            discovery_method: "Demo".to_string(),
            system_description: None,
            uptime_seconds: None,
            is_randomized: true,
            neighbors: vec![],
            vulnerabilities: vec![],
            port_warnings: vec![],
            security_grade: "A".to_string(),
        },
        
        // 4. Network Printer
        HostInfo {
            ip: "192.168.1.30".to_string(),
            mac: "00:25:b3:a4:56:78".to_string(),
            vendor: Some("Hewlett Packard".to_string()),
            hostname: Some("HP-Printer-01".to_string()),
            device_type: "Printer".to_string(),
            os_guess: None,
            response_time_ms: Some(3),
            ttl: Some(64),
            open_ports: vec![80, 631, 9100],
            risk_score: 40,
            discovery_method: "Demo".to_string(),
            system_description: None,
            uptime_seconds: None,
            is_randomized: false,
            neighbors: vec![],
            vulnerabilities: vec![],
            port_warnings: vec![],
            security_grade: "C".to_string(),
        },
        
        // 5. IP Camera - HIGH RISK
        HostInfo {
            ip: "192.168.1.70".to_string(),
            mac: "44:19:b6:12:34:56".to_string(),
            vendor: Some("Hangzhou Hikvision Digital".to_string()),
            hostname: Some("IP-Camera-Front".to_string()),
            device_type: "Camera".to_string(),
            os_guess: None,
            response_time_ms: Some(10),
            ttl: Some(64),
            open_ports: vec![80, 554],
            risk_score: 60,
            discovery_method: "Demo".to_string(),
            system_description: None,
            uptime_seconds: None,
            is_randomized: false,
            neighbors: vec![],
            vulnerabilities: vec![
                VulnerabilityInfo {
                    cve_id: "CVE-2021-36260".to_string(),
                    severity: "Critical".to_string(),
                    description: "Hikvision IP Camera Command Injection".to_string(),
                    cvss_score: Some(9.8),
                },
            ],
            port_warnings: vec![],
            security_grade: "D".to_string(),
        },
        
        // 6. Managed Switch (Cisco)
        HostInfo {
            ip: "192.168.1.2".to_string(),
            mac: "00:1e:14:7b:3c:90".to_string(),
            vendor: Some("Cisco Systems, Inc.".to_string()),
            hostname: Some("SW-Core-01".to_string()),
            device_type: "Switch".to_string(),
            os_guess: Some("Cisco IOS".to_string()),
            response_time_ms: Some(1),
            ttl: Some(255),
            open_ports: vec![22, 23, 80, 443],
            risk_score: 25,
            discovery_method: "Demo".to_string(),
            system_description: None,
            uptime_seconds: None,
            is_randomized: false,
            neighbors: vec![],
            vulnerabilities: vec![],
            port_warnings: vec![],
            security_grade: "B".to_string(),
        },
        
        // 7. MacBook Pro
        HostInfo {
            ip: "192.168.1.15".to_string(),
            mac: "3c:22:fb:89:12:34".to_string(),
            vendor: Some("Apple, Inc.".to_string()),
            hostname: Some("MacBook-Pro.local".to_string()),
            device_type: "Laptop".to_string(),
            os_guess: Some("Linux/Unix/macOS".to_string()),
            response_time_ms: Some(4),
            ttl: Some(64),
            open_ports: vec![],
            risk_score: 15,
            discovery_method: "Demo".to_string(),
            system_description: None,
            uptime_seconds: None,
            is_randomized: false,
            neighbors: vec![],
            vulnerabilities: vec![],
            port_warnings: vec![],
            security_grade: "A".to_string(),
        },
        
        // 8. iPhone (Randomized MAC)
        HostInfo {
            ip: "192.168.1.26".to_string(),
            mac: "f2:a3:b4:c5:d6:e7".to_string(),
            vendor: Some("Private Device (Randomized MAC)".to_string()),
            hostname: Some("iPhone-14".to_string()),
            device_type: "Phone".to_string(),
            os_guess: Some("Linux/Unix/macOS".to_string()),
            response_time_ms: Some(15),
            ttl: Some(64),
            open_ports: vec![],
            risk_score: 10,
            discovery_method: "Demo".to_string(),
            system_description: None,
            uptime_seconds: None,
            is_randomized: true,
            neighbors: vec![],
            vulnerabilities: vec![],
            port_warnings: vec![],
            security_grade: "A".to_string(),
        },
        
        // 9. Smart TV (Samsung)
        HostInfo {
            ip: "192.168.1.40".to_string(),
            mac: "e8:50:8b:12:34:56".to_string(),
            vendor: Some("Samsung Electronics Co., Ltd.".to_string()),
            hostname: Some("Samsung-TV".to_string()),
            device_type: "SmartTV".to_string(),
            os_guess: Some("Tizen OS".to_string()),
            response_time_ms: Some(8),
            ttl: Some(64),
            open_ports: vec![8001, 8002],
            risk_score: 30,
            discovery_method: "Demo".to_string(),
            system_description: None,
            uptime_seconds: None,
            is_randomized: false,
            neighbors: vec![],
            vulnerabilities: vec![],
            port_warnings: vec![],
            security_grade: "C".to_string(),
        },
        
        // 10. Raspberry Pi Server
        HostInfo {
            ip: "192.168.1.50".to_string(),
            mac: "b8:27:eb:45:67:89".to_string(),
            vendor: Some("Raspberry Pi Foundation".to_string()),
            hostname: Some("RasPi-Server".to_string()),
            device_type: "Server".to_string(),
            os_guess: Some("Linux/Unix/macOS".to_string()),
            response_time_ms: Some(3),
            ttl: Some(64),
            open_ports: vec![22, 80, 3306],
            risk_score: 50,
            discovery_method: "Demo".to_string(),
            system_description: None,
            uptime_seconds: None,
            is_randomized: false,
            neighbors: vec![],
            vulnerabilities: vec![
                VulnerabilityInfo {
                    cve_id: "CVE-2023-4911".to_string(),
                    severity: "High".to_string(),
                    description: "Looney Tunables - glibc buffer overflow".to_string(),
                    cvss_score: Some(7.8),
                },
            ],
            port_warnings: vec![],
            security_grade: "D".to_string(),
        },
        
        // 11. NAS Storage (Synology)
        HostInfo {
            ip: "192.168.1.60".to_string(),
            mac: "00:11:32:ab:cd:ef".to_string(),
            vendor: Some("Synology Incorporated".to_string()),
            hostname: Some("NAS-Storage".to_string()),
            device_type: "Storage".to_string(),
            os_guess: Some("Linux/Unix/macOS".to_string()),
            response_time_ms: Some(4),
            ttl: Some(64),
            open_ports: vec![80, 443, 5000, 5001],
            risk_score: 35,
            discovery_method: "Demo".to_string(),
            system_description: None,
            uptime_seconds: None,
            is_randomized: false,
            neighbors: vec![],
            vulnerabilities: vec![],
            port_warnings: vec![],
            security_grade: "B".to_string(),
        },
        
        // 12. Wireless Access Point
        HostInfo {
            ip: "192.168.1.3".to_string(),
            mac: "24:a4:3c:56:78:90".to_string(),
            vendor: Some("Ubiquiti Networks Inc.".to_string()),
            hostname: Some("UAP-AC-Pro".to_string()),
            device_type: "AccessPoint".to_string(),
            os_guess: Some("Linux/Unix/macOS".to_string()),
            response_time_ms: Some(2),
            ttl: Some(64),
            open_ports: vec![22, 80, 443],
            risk_score: 20,
            discovery_method: "Demo".to_string(),
            system_description: None,
            uptime_seconds: None,
            is_randomized: false,
            neighbors: vec![],
            vulnerabilities: vec![],
            port_warnings: vec![],
            security_grade: "A".to_string(),
        },
        
        // 13. Xbox Gaming Console
        HostInfo {
            ip: "192.168.1.45".to_string(),
            mac: "98:5f:d3:12:34:56".to_string(),
            vendor: Some("Microsoft Corporation".to_string()),
            hostname: Some("Xbox-Series-X".to_string()),
            device_type: "Gaming".to_string(),
            os_guess: Some("Xbox OS".to_string()),
            response_time_ms: Some(6),
            ttl: Some(128),
            open_ports: vec![],
            risk_score: 15,
            discovery_method: "Demo".to_string(),
            system_description: None,
            uptime_seconds: None,
            is_randomized: false,
            neighbors: vec![],
            vulnerabilities: vec![],
            port_warnings: vec![],
            security_grade: "A".to_string(),
        },
        
        // 14. Canon Printer
        HostInfo {
            ip: "192.168.1.31".to_string(),
            mac: "00:1e:8f:ab:cd:12".to_string(),
            vendor: Some("Canon Inc.".to_string()),
            hostname: Some("Canon-MX920".to_string()),
            device_type: "Printer".to_string(),
            os_guess: None,
            response_time_ms: Some(5),
            ttl: Some(64),
            open_ports: vec![80, 631],
            risk_score: 38,
            discovery_method: "Demo".to_string(),
            system_description: None,
            uptime_seconds: None,
            is_randomized: false,
            neighbors: vec![],
            vulnerabilities: vec![],
            port_warnings: vec![],
            security_grade: "C".to_string(),
        },
        
        // 15. Amazon Echo Dot
        HostInfo {
            ip: "192.168.1.41".to_string(),
            mac: "50:dc:e7:89:12:34".to_string(),
            vendor: Some("Amazon Technologies Inc.".to_string()),
            hostname: Some("Echo-Dot".to_string()),
            device_type: "IoT".to_string(),
            os_guess: Some("Fire OS".to_string()),
            response_time_ms: Some(7),
            ttl: Some(64),
            open_ports: vec![],
            risk_score: 25,
            discovery_method: "Demo".to_string(),
            system_description: None,
            uptime_seconds: None,
            is_randomized: false,
            neighbors: vec![],
            vulnerabilities: vec![],
            port_warnings: vec![],
            security_grade: "B".to_string(),
        },
        
        // 16. Linux Workstation (HP)
        HostInfo {
            ip: "192.168.1.20".to_string(),
            mac: "3c:52:82:1f:34:b8".to_string(),
            vendor: Some("Hewlett Packard".to_string()),
            hostname: Some("HP-Workstation".to_string()),
            device_type: "Desktop".to_string(),
            os_guess: Some("Linux/Unix/macOS".to_string()),
            response_time_ms: Some(3),
            ttl: Some(64),
            open_ports: vec![22],
            risk_score: 20,
            discovery_method: "Demo".to_string(),
            system_description: None,
            uptime_seconds: None,
            is_randomized: false,
            neighbors: vec![],
            vulnerabilities: vec![],
            port_warnings: vec![],
            security_grade: "A".to_string(),
        },
    ]
}

/// Generate sample alert records
pub fn generate_demo_alerts() -> Vec<AlertRecord> {
    let now = chrono::Utc::now();
    
    vec![
        AlertRecord {
            id: 1,
            created_at: now - chrono::Duration::hours(2),
            alert_type: AlertType::NewDevice,
            device_id: Some(3),
            device_mac: Some("d2:81:c8:45:6b:71".to_string()),
            device_ip: Some("192.168.1.25".to_string()),

            message: "New device detected: Galaxy-S23 (Private Device)".to_string(),
            severity: AlertSeverity::Info,
            is_read: false,
        },
        AlertRecord {
            id: 2,
            created_at: now - chrono::Duration::hours(5),
            alert_type: AlertType::HighRisk,
            device_id: Some(2),
            device_mac: Some("00:0c:29:5a:8f:1d".to_string()),
            device_ip: Some("192.168.1.10".to_string()),
            message: "High risk device: WIN-PC-001 has critical vulnerabilities (EternalBlue, BlueKeep)".to_string(),
            severity: AlertSeverity::Critical,
            is_read: false,
        },
        AlertRecord {
            id: 3,
            created_at: now - chrono::Duration::days(1),
            alert_type: AlertType::PortChange,
            device_id: Some(5),
            device_mac: Some("44:19:b6:12:34:56".to_string()),
            device_ip: Some("192.168.1.70".to_string()),
            message: "New port detected on IP-Camera-Front: RTSP (554)".to_string(),
            severity: AlertSeverity::Warning,
            is_read: true,
        },
    ]
}
